version: 2.1

commands:
  prepare_python_env:
    description: "Common prepare steps for all jobs"
    steps:
      - checkout
      - run:
          name: install dependencies
          command: poetry install
jobs:
  demo:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - prepare_python_env
      - run:
          name: "Say hello"
          command: "poetry run python --version"

workflows:
  version: 2
  demo_cron:
    triggers:
      - schedule:
          cron: "17 07 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - demo