commands:
  prepare_python_env:
    description: Common prepare steps for all jobs
    steps:
    - checkout
    - run:
        command: poetry install
        name: install dependencies
jobs:
  check_weather_job:
    docker:
    - image: cimg/python:3.10.2
    steps:
    - prepare_python_env
    - run:
        command: poetry run python jobs/check_weather.py
        name: Run
version: 2.1
workflows:
  check_weather_cron:
    jobs:
    - check_weather_job
    triggers:
    - schedule:
        cron: 30,45,59 12 * * *
        filters:
          branches:
            only:
            - main
